import { CONFIG, MOVEMENT } from "../config.js";
import { OBSTACLE_LOG_PRESETS, OBSTACLE_VINE_PRESETS, OBSTACLE_CROC_RIVER_PRESETS } from "../level-elements/obstacle-presets.js";
import { ENEMY_MONKEY_PATROL_PRESETS } from "../level-elements/enemy-presets.js";
import { COLLECTIBLE_PINEAPPLE_PRESETS } from "../level-elements/collectible-presets.js";
import { LEVEL_2 } from "./level2.js";

export const LEVEL_3 = {
  id: "level-3",
  name: "Night Run",
  background: "sunset-temple-run",
  theme: LEVEL_2.theme,
  speed: { ...MOVEMENT, maxSpeed: 42 },
  course: {
    floorLength: 1500,
    gateZ: -1330,
    finishLineZ: -1330,
    endOfCourseZ: -1352,
  },
  loops: [0, 245, 490, 735, 980],
  loopPlans: [
    {
      swayWidth: 1.7,
      guideX: 0,
      guideCount: 8,
      swayCount: 6,
      jumpCount: 5,
      highCount: 5,
      slideCount: 5,
      crateFruitCount: 4,
      jumpX: 0,
      highX: 0,
      slideX: 0,
      crateFruitStartX: -0.85,
      crateFruitEndX: 0.85,
      log: { ...OBSTACLE_LOG_PRESETS[0] },
      branch: { ...OBSTACLE_VINE_PRESETS[0] },
      crates: [{ localX: 0, z: 184 }],
      river: { ...OBSTACLE_CROC_RIVER_PRESETS[0], crocs: [...OBSTACLE_CROC_RIVER_PRESETS[0].crocs] },
      health: { localX: 0, z: 240 },
      enemies: ENEMY_MONKEY_PATROL_PRESETS[0].map((enemy) => ({ ...enemy })),
      pineapples: COLLECTIBLE_PINEAPPLE_PRESETS[0].map((pineapple) => ({ ...pineapple })),
    },
    {
      swayWidth: 2.95,
      guideX: 0,
      guideCount: 8,
      swayCount: 8,
      jumpCount: 6,
      highCount: 7,
      slideCount: 6,
      crateFruitCount: 5,
      jumpX: -0.75,
      highX: 1.4,
      slideX: -1.1,
      crateFruitStartX: 2.2,
      crateFruitEndX: -2.2,
      log: { ...OBSTACLE_LOG_PRESETS[1] },
      branch: { ...OBSTACLE_VINE_PRESETS[1] },
      crates: [{ localX: -1.45, z: 184 }, { localX: 2.85, z: 184 }],
      river: { ...OBSTACLE_CROC_RIVER_PRESETS[1], crocs: [...OBSTACLE_CROC_RIVER_PRESETS[1].crocs] },
      health: { localX: -1.8, z: 240 },
      enemies: ENEMY_MONKEY_PATROL_PRESETS[1].map((enemy) => ({ ...enemy })),
      pineapples: COLLECTIBLE_PINEAPPLE_PRESETS[1].map((pineapple) => ({ ...pineapple })),
    },
    {
      swayWidth: 3.25,
      guideX: -0.45,
      guideCount: 7,
      swayCount: 9,
      jumpCount: 6,
      highCount: 8,
      slideCount: 6,
      crateFruitCount: 7,
      jumpX: 1.2,
      highX: -2.05,
      slideX: 1.65,
      crateFruitStartX: -3.1,
      crateFruitEndX: 3.1,
      log: { ...OBSTACLE_LOG_PRESETS[2] },
      branch: { ...OBSTACLE_VINE_PRESETS[2] },
      crates: [{ localX: 0, z: 184 }, { localX: -3.05, z: 184 }, { localX: 3.05, z: 184 }, { localX: 1.55, z: 198 }],
      river: { ...OBSTACLE_CROC_RIVER_PRESETS[2], crocs: [...OBSTACLE_CROC_RIVER_PRESETS[2].crocs] },
      health: { localX: 2.2, z: 240 },
      enemies: ENEMY_MONKEY_PATROL_PRESETS[2].map((enemy) => ({ ...enemy })),
      pineapples: COLLECTIBLE_PINEAPPLE_PRESETS[2].map((pineapple) => ({ ...pineapple })),
    },
    {
      swayWidth: 3.55,
      guideX: 0.65,
      guideCount: 7,
      swayCount: 10,
      jumpCount: 7,
      highCount: 8,
      slideCount: 7,
      crateFruitCount: 8,
      jumpX: -1.5,
      highX: 2.4,
      slideX: -2.1,
      crateFruitStartX: 3.45,
      crateFruitEndX: -3.45,
      log: { ...OBSTACLE_LOG_PRESETS[3] },
      branch: { ...OBSTACLE_VINE_PRESETS[3] },
      crates: [
        { localX: -0.55, z: 184 },
        { localX: 2.95, z: 184 },
        { localX: -3.25, z: 184 },
        { localX: 1.45, z: 198 },
      ],
      river: { ...OBSTACLE_CROC_RIVER_PRESETS[3], crocs: [...OBSTACLE_CROC_RIVER_PRESETS[3].crocs] },
      health: { localX: -2.35, z: 240 },
      enemies: ENEMY_MONKEY_PATROL_PRESETS[3].map((enemy) => ({ ...enemy })),
      pineapples: COLLECTIBLE_PINEAPPLE_PRESETS[3].map((pineapple) => ({ ...pineapple })),
    },
    {
      swayWidth: 3.85,
      guideX: -0.9,
      guideCount: 6,
      swayCount: 11,
      jumpCount: 8,
      highCount: 9,
      slideCount: 8,
      crateFruitCount: 9,
      jumpX: 2.05,
      highX: -2.75,
      slideX: 2.5,
      crateFruitStartX: -3.95,
      crateFruitEndX: 3.95,
      log: { ...OBSTACLE_LOG_PRESETS[4] },
      branch: { ...OBSTACLE_VINE_PRESETS[4] },
      crates: [
        { localX: 0, z: 184 },
        { localX: -3.35, z: 184 },
        { localX: 3.35, z: 184 },
        { localX: -1.65, z: 198 },
        { localX: 1.65, z: 198 },
      ],
      river: { ...OBSTACLE_CROC_RIVER_PRESETS[4], crocs: [...OBSTACLE_CROC_RIVER_PRESETS[4].crocs] },
      health: { localX: 2.65, z: 240 },
      enemies: ENEMY_MONKEY_PATROL_PRESETS[4].map((enemy) => ({ ...enemy })),
      pineapples: COLLECTIBLE_PINEAPPLE_PRESETS[4].map((pineapple) => ({ ...pineapple })),
    },
  ],
  goalDistance: Math.abs(-1330),
  music: "main-theme",
  nextLevel: null,
};

export default LEVEL_3;
