import { CONFIG, MOVEMENT } from "../config.js";
import { OBSTACLE_LOG_PRESETS, OBSTACLE_VINE_PRESETS, OBSTACLE_CROC_RIVER_PRESETS } from "../level-elements/obstacle-presets.js";
import { ENEMY_MONKEY_PATROL_LEVEL1_PRESETS } from "../level-elements/enemy-presets.js";
import { COLLECTIBLE_PINEAPPLE_PRESETS } from "../level-elements/collectible-presets.js";

// Level 1 gameplay values are intentionally fixed; only progression uses `nextLevel`.
export const LEVEL_1 = {
  id: "level-1",
  name: "Level 1",
  background: "jungle-day",
  speed: { ...MOVEMENT },
  loops: [0, 245, 490],
  loopPlans: [
    {
      swayWidth: 1.45,
      guideX: 0,
      guideCount: 8,
      swayCount: 6,
      jumpCount: 5,
      highCount: 5,
      slideCount: 5,
      crateFruitCount: 4,
      jumpX: 0,
      highX: 0,
      slideX: 0,
      crateFruitStartX: -0.55,
      crateFruitEndX: 0.55,
      log: { ...OBSTACLE_LOG_PRESETS[0] },
      branch: { ...OBSTACLE_VINE_PRESETS[0] },
      crates: [{ localX: 0, z: 184 }],
      river: { ...OBSTACLE_CROC_RIVER_PRESETS[0], crocs: [...OBSTACLE_CROC_RIVER_PRESETS[0].crocs] },
      health: { localX: 0, z: 240 },
      enemies: ENEMY_MONKEY_PATROL_LEVEL1_PRESETS[0].map((enemy) => ({ ...enemy })),
      pineapples: COLLECTIBLE_PINEAPPLE_PRESETS[0].map((pineapple) => ({ ...pineapple })),
    },
    {
      swayWidth: 2.65,
      guideX: 0,
      guideCount: 8,
      swayCount: 8,
      jumpCount: 6,
      highCount: 7,
      slideCount: 6,
      crateFruitCount: 5,
      jumpX: -0.75,
      highX: 1.4,
      slideX: -1.1,
      crateFruitStartX: 1.6,
      crateFruitEndX: -1.6,
      log: { ...OBSTACLE_LOG_PRESETS[1] },
      branch: { ...OBSTACLE_VINE_PRESETS[1] },
      crates: [{ localX: -1.45, z: 184 }, { localX: 2.85, z: 184 }],
      river: { ...OBSTACLE_CROC_RIVER_PRESETS[1], crocs: [...OBSTACLE_CROC_RIVER_PRESETS[1].crocs] },
      health: { localX: -1.8, z: 240 },
      enemies: ENEMY_MONKEY_PATROL_LEVEL1_PRESETS[1].map((enemy) => ({ ...enemy })),
      pineapples: COLLECTIBLE_PINEAPPLE_PRESETS[1].map((pineapple) => ({ ...pineapple })),
    },
    {
      swayWidth: 2.95,
      guideX: -0.45,
      guideCount: 7,
      swayCount: 9,
      jumpCount: 6,
      highCount: 8,
      slideCount: 6,
      crateFruitCount: 6,
      jumpX: 1.2,
      highX: -2.05,
      slideX: 1.65,
      crateFruitStartX: -2.6,
      crateFruitEndX: 2.6,
      log: { ...OBSTACLE_LOG_PRESETS[2] },
      branch: { ...OBSTACLE_VINE_PRESETS[2] },
      crates: [{ localX: 0, z: 184 }, { localX: -3.05, z: 184 }, { localX: 3.05, z: 184 }],
      river: { ...OBSTACLE_CROC_RIVER_PRESETS[2], crocs: [...OBSTACLE_CROC_RIVER_PRESETS[2].crocs] },
      health: { localX: 2.2, z: 240 },
      enemies: ENEMY_MONKEY_PATROL_LEVEL1_PRESETS[2].map((enemy) => ({ ...enemy })),
      pineapples: COLLECTIBLE_PINEAPPLE_PRESETS[2].map((pineapple) => ({ ...pineapple })),
    },
  ],
  goalDistance: CONFIG.finishLineZ,
  music: "main-theme",
  nextLevel: "level-2",
};

export default LEVEL_1;
